export const GENERATED_EXERCISE_IMAGE_MANIFEST: Record<string, string> = {
  "empathy-b1-backsquat": "empathy-b1-backsquat-v2.png",
  "empathy-b1-deadlift": "empathy-b1-deadlift-v2.png",
  "empathy-b1-bench": "empathy-b1-bench-v2.png",
  "empathy-b1-ohpress": "empathy-b1-ohpress-v2.png",
  "empathy-b1-latpulldown": "empathy-b1-latpulldown-v2.png",
  "empathy-b1-rowerg": "empathy-b1-rowerg-v2.png",
  "empathy-b1-skierg": "empathy-b1-skierg-v2.png",
  "empathy-b1-thruster": "empathy-b1-thruster-v2.png",
  "empathy-b1-wallball": "empathy-b1-wallball-v2.png",
  "empathy-b1-kbswing": "empathy-b1-kbswing-v2.png",
  "empathy-b1-ttb": "empathy-b1-ttb-v2.png",
  "empathy-b1-burpee": "empathy-b1-burpee-v2.png",
  "empathy-b1-sledpush": "empathy-b1-sledpush-v2.png",
  "empathy-b1-farmer": "empathy-b1-farmer-v2.png",
  "empathy-b1-plank": "empathy-b1-plank-v2.png",
  "empathy-b1-intervalrun": "empathy-b1-intervalrun-v2.png",
  "empathy-b1-cablefly": "empathy-b1-cablefly-v2.png",
  "empathy-b1-inclinedbpress": "empathy-b1-inclinedbpress-v2.png",
  "empathy-b1-machinechestpress": "empathy-b1-machinechestpress-v2.png",
  "empathy-b1-weighteddip": "empathy-b1-weighteddip-v2.png",
  "empathy-b1-lateralraise": "empathy-b1-lateralraise-v2.png",
  "empathy-b1-pause-squat": "empathy-b1-pause-squat-v2.png",
  "empathy-b1-rdl": "empathy-b1-rdl-v2.png",
  "empathy-b1-legpress": "empathy-b1-legpress-v2.png",
  "empathy-b1-wlunge": "empathy-b1-wlunge-v2.png",
  "empathy-b1x-hacksquat": "empathy-b1x-hacksquat-v2.png",
  "empathy-b1x-beltsquat": "empathy-b1x-beltsquat-v2.png",
  "empathy-b1x-pendulumsquat": "empathy-b1x-pendulumsquat-v2.png",
  "empathy-b1x-smithsquat": "empathy-b1x-smithsquat-v2.png",
  "empathy-b1x-landminesquat": "empathy-b1x-landminesquat-v2.png",
  "empathy-b1x-trapbardeadlift": "empathy-b1x-trapbardeadlift-v2.png",
  "empathy-b1x-reverselunge": "empathy-b1x-reverselunge-v2.png",
  "empathy-b1x-heelselevatedsquat": "empathy-b1x-heelselevatedsquat-v2.png",
  "empathy-b1x-zerchersquat": "empathy-b1x-zerchersquat-v2.png",
  "empathy-b1x-safetybarsquat": "empathy-b1x-safetybarsquat-v2.png",
  "empathy-b1x-laterallunge": "empathy-b1x-laterallunge-v2.png",
  "empathy-b1x-cossacksquat": "empathy-b1x-cossacksquat-v2.png",
  "empathy-b1x-stepdown": "empathy-b1x-stepdown-v2.png",
  "empathy-b1x-pistolsquat": "empathy-b1x-pistolsquat-v2.png",
  "empathy-b1x-spanishsquat": "empathy-b1x-spanishsquat-v2.png",
  "empathy-b1x-cyclistsquat": "empathy-b1x-cyclistsquat-v2.png",
  "empathy-b1x-deficitdeadlift": "empathy-b1x-deficitdeadlift-v2.png",
  "empathy-b1x-sumodeadlift": "empathy-b1x-sumodeadlift-v2.png",
  "empathy-b1x-stifflegdeadlift": "empathy-b1x-stifflegdeadlift-v2.png",
  "empathy-b1x-nordiccurl": "empathy-b1x-nordiccurl-v2.png",
  "empathy-b1x-glutehamraise": "empathy-b1x-glutehamraise-v2.png",
  "empathy-b1x-seatedlegcurl": "empathy-b1x-seatedlegcurl-v2.png",
  "empathy-b1x-singlelegpress": "empathy-b1x-singlelegpress-v2.png",
  "empathy-b1x-singlelegextension": "empathy-b1x-singlelegextension-v2.png",
  "empathy-b1x-cablepullthrough": "empathy-b1x-cablepullthrough-v2.png",
  "empathy-b1x-frogpump": "empathy-b1x-frogpump-v2.png",
  "empathy-b1x-donkeycalfraise": "empathy-b1x-donkeycalfraise-v2.png",
  "empathy-b1x-tibialisraise": "empathy-b1x-tibialisraise-v2.png",
  "empathy-b1x-smithsplitsquat": "empathy-b1x-smithsplitsquat-v2.png",
  "empathy-b1x-frontfootelevatedsplit": "empathy-b1x-frontfootelevatedsplit-v2.png",
  "empathy-b1x-inclinebarbellpress": "empathy-b1x-inclinebarbellpress-v2.png",
  "empathy-b1x-declinebenchpress": "empathy-b1x-declinebenchpress-v2.png",
  "empathy-b1x-dumbbellbenchpress": "empathy-b1x-dumbbellbenchpress-v2.png",
  "empathy-b1x-dumbbellshoulderpress": "empathy-b1x-dumbbellshoulderpress-v2.png",
  "empathy-b1x-arnoldpress": "empathy-b1x-arnoldpress-v2.png",
  "empathy-b1x-landminepress": "empathy-b1x-landminepress-v2.png",
  "empathy-b1x-pushpress": "empathy-b1x-pushpress-v2.png",
  "empathy-b1x-machineshoulderpress": "empathy-b1x-machineshoulderpress-v2.png",
  "empathy-b1x-smithbenchpress": "empathy-b1x-smithbenchpress-v2.png",
  "empathy-b1x-floorpress": "empathy-b1x-floorpress-v2.png",
  "empathy-b1x-chinup": "empathy-b1x-chinup-v2.png",
  "empathy-b1x-assistedpullup": "empathy-b1x-assistedpullup-v2.png",
  "empathy-b1x-neutralgrippulldown": "empathy-b1x-neutralgrippulldown-v2.png",
  "empathy-b1x-singlearmpulldown": "empathy-b1x-singlearmpulldown-v2.png",
  "empathy-b1x-singlearmrow": "empathy-b1x-singlearmrow-v2.png",
  "empathy-b1x-sealrow": "empathy-b1x-sealrow-v2.png",
  "empathy-b1x-invertedrow": "empathy-b1x-invertedrow-v2.png",
  "empathy-b1x-meadowsrow": "empathy-b1x-meadowsrow-v2.png",
  "empathy-b1x-machinehighrow": "empathy-b1x-machinehighrow-v2.png",
  "empathy-b1x-machinelowrow": "empathy-b1x-machinelowrow-v2.png",
  "empathy-b1x-cablepullover": "empathy-b1x-cablepullover-v2.png",
  "empathy-b1x-machinepullover": "empathy-b1x-machinepullover-v2.png",
  "empathy-b1x-shrug": "empathy-b1x-shrug-v2.png",
  "empathy-b1x-inclinecurl": "empathy-b1x-inclinecurl-v2.png",
  "empathy-b1x-concentrationcurl": "empathy-b1x-concentrationcurl-v2.png",
  "empathy-b1x-spidercurl": "empathy-b1x-spidercurl-v2.png",
  "empathy-b1x-cablecurl": "empathy-b1x-cablecurl-v2.png",
  "empathy-b1x-preacherhammercurl": "empathy-b1x-preacherhammercurl-v2.png",
  "empathy-b1x-wristcurl": "empathy-b1x-wristcurl-v2.png",
  "empathy-b1x-reversewristcurl": "empathy-b1x-reversewristcurl-v2.png",
  "empathy-b1x-zottmancurl": "empathy-b1x-zottmancurl-v2.png",
  "empathy-b1x-trapbarshrug": "empathy-b1x-trapbarshrug-v2.png",
  "empathy-b1x-yraise": "empathy-b1x-yraise-v2.png",
  "empathy-b1x-bandpullapart": "empathy-b1x-bandpullapart-v2.png",
  "empathy-b1x-scappullup": "empathy-b1x-scappullup-v2.png",
  "empathy-b1x-widegripseatedrow": "empathy-b1x-widegripseatedrow-v2.png",
  "empathy-b1x-ropehammercurl": "empathy-b1x-ropehammercurl-v2.png",
  "empathy-b1x-rackpull": "empathy-b1x-rackpull-v2.png",
  "empathy-b1x-deadbug": "empathy-b1x-deadbug-v2.png",
  "empathy-b1x-hollowhold": "empathy-b1x-hollowhold-v2.png",
  "empathy-b1x-pallofpress": "empathy-b1x-pallofpress-v2.png",
  "empathy-b1x-sideplank": "empathy-b1x-sideplank-v2.png",
  "empathy-b1x-weightedsitup": "empathy-b1x-weightedsitup-v2.png",
  "empathy-b1x-hanginglegraise": "empathy-b1x-hanginglegraise-v2.png",
  "empathy-b1x-cablecrunch": "empathy-b1x-cablecrunch-v2.png",
  "empathy-b1x-reversecrunch": "empathy-b1x-reversecrunch-v2.png",
  "empathy-b1x-mountainclimber": "empathy-b1x-mountainclimber-v2.png",
  "empathy-b1x-birddog": "empathy-b1x-birddog-v2.png",
  "empathy-b1x-suitcasecarry": "empathy-b1x-suitcasecarry-v2.png",
  "empathy-b1x-waitercarry": "empathy-b1x-waitercarry-v2.png",
  "empathy-b1x-stirthepot": "empathy-b1x-stirthepot-v2.png",
  "empathy-b1x-bodysaw": "empathy-b1x-bodysaw-v2.png",
  "empathy-b1x-dragonflag": "empathy-b1x-dragonflag-v2.png",
  "empathy-b1x-landminerotation": "empathy-b1x-landminerotation-v2.png",
  "empathy-b1x-woodchop": "empathy-b1x-woodchop-v2.png",
  "empathy-b1x-backextension": "empathy-b1x-backextension-v2.png",
  "empathy-b1x-supermanhold": "empathy-b1x-supermanhold-v2.png",
  "empathy-b1x-openhagenadduction": "empathy-b1x-openhagenadduction-v2.png",
  "empathy-b1x-assaultbike": "empathy-b1x-assaultbike-v2.png",
  "empathy-b1x-echobike": "empathy-b1x-echobike-v2.png",
  "empathy-b1x-battleropes": "empathy-b1x-battleropes-v2.png",
  "empathy-b1x-shuttlerun": "empathy-b1x-shuttlerun-v2.png",
  "empathy-b1x-bearcrawl": "empathy-b1x-bearcrawl-v2.png",
  "empathy-b1x-crabwalk": "empathy-b1x-crabwalk-v2.png",
  "empathy-b1x-boxstepover": "empathy-b1x-boxstepover-v2.png",
  "empathy-b1x-broadjump": "empathy-b1x-broadjump-v2.png",
  "empathy-b1x-sleddragbackward": "empathy-b1x-sleddragbackward-v2.png",
  "empathy-b1x-sandbagcarry": "empathy-b1x-sandbagcarry-v2.png",
  "empathy-b1x-sandbaglunge": "empathy-b1x-sandbaglunge-v2.png",
  "empathy-b1x-devilpress": "empathy-b1x-devilpress-v2.png",
};

const GENERATED_EXERCISE_IMAGE_PUBLIC_DIR = "/assets/empathy/exercises/generated";

/**
 * URL servita da `apps/web/public/assets/empathy/exercises/generated/` (allineamento V1).
 */
export function publicUrlForGeneratedExerciseImage(exerciseId: string): string | null {
  const id = exerciseId.trim();
  const file = GENERATED_EXERCISE_IMAGE_MANIFEST[id];
  if (!file) return null;
  if (/[/\\]|\.\./.test(file)) return null;
  return `${GENERATED_EXERCISE_IMAGE_PUBLIC_DIR}/${file}`;
}
