import type { ExerciseLibraryItem } from "@/lib/training/engine/types";

export const TRAINING_EXERCISE_LIBRARY: ExerciseLibraryItem[] = [
  {
    id: "gym_back_squat",
    name: "Back Squat",
    domain: "gym",
    sportTags: ["gym", "crossfit", "hyrox"],
    movementPattern: "squat",
    muscleGroups: ["quadriceps", "glutes", "core"],
    equipment: ["barbell", "rack"],
    physiology: {
      primarySystem: "neuromuscular_strength",
      secondarySystems: ["anaerobic_lactic", "stability"],
      adaptationTargets: [
        "max_strength",
        "hypertrophy_mixed",
        "hypertrophy_myofibrillar",
        "hypertrophy_sarcoplasmic",
        "neuromuscular_adaptation",
        "lactate_tolerance",
      ],
      loadBand: "high",
      lactateImpact: "medium",
      cnsLoad: "high",
    },
    skills: { coordination: "medium", balance: "medium", techniqueLevel: "high" },
  },
  {
    id: "gym_pull_up",
    name: "Pull-up / chin-up",
    domain: "gym",
    sportTags: ["gym", "crossfit"],
    movementPattern: "vertical_pull",
    muscleGroups: ["lats", "biceps", "core"],
    equipment: ["pullup_bar", "bodyweight"],
    gymMeta: { channels: ["bodyweight"], contractions: ["standard"] },
    physiology: {
      primarySystem: "neuromuscular_strength",
      secondarySystems: ["coordination", "stability"],
      adaptationTargets: [
        "max_strength",
        "hypertrophy_mixed",
        "hypertrophy_myofibrillar",
        "neuromuscular_adaptation",
        "movement_quality",
      ],
      loadBand: "high",
      lactateImpact: "low",
      cnsLoad: "medium",
    },
    skills: { coordination: "medium", balance: "medium", techniqueLevel: "high" },
  },
  {
    id: "gym_cable_standing_row",
    name: "Standing cable row",
    domain: "gym",
    sportTags: ["gym", "hyrox"],
    movementPattern: "horizontal_pull",
    muscleGroups: ["lats", "rear_delt", "core"],
    equipment: ["cable"],
    gymMeta: { channels: ["cable"] },
    physiology: {
      primarySystem: "neuromuscular_strength",
      secondarySystems: ["stability"],
      adaptationTargets: [
        "hypertrophy_mixed",
        "hypertrophy_sarcoplasmic",
        "hypertrophy_myofibrillar",
        "movement_quality",
        "max_strength",
      ],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "medium",
    },
    skills: { coordination: "low", balance: "medium", techniqueLevel: "medium" },
  },
  {
    id: "gym_band_squat",
    name: "Band-resisted squat",
    domain: "gym",
    sportTags: ["gym"],
    movementPattern: "squat",
    muscleGroups: ["quadriceps", "glutes", "core"],
    equipment: ["band", "rack"],
    gymMeta: { channels: ["elastic", "free_weight"] },
    physiology: {
      primarySystem: "neuromuscular_strength",
      secondarySystems: ["stability"],
      adaptationTargets: [
        "neuromuscular_adaptation",
        "hypertrophy_mixed",
        "power_output",
        "movement_quality",
      ],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "medium",
    },
    skills: { coordination: "medium", balance: "medium", techniqueLevel: "medium" },
  },
  {
    id: "gym_leg_press",
    name: "Leg press (machine)",
    domain: "gym",
    sportTags: ["gym", "hyrox"],
    movementPattern: "squat",
    muscleGroups: ["quadriceps", "glutes"],
    equipment: ["machine", "leg_press"],
    gymMeta: { channels: ["machine"] },
    physiology: {
      primarySystem: "neuromuscular_strength",
      secondarySystems: ["anaerobic_lactic", "stability"],
      adaptationTargets: [
        "hypertrophy_mixed",
        "hypertrophy_sarcoplasmic",
        "hypertrophy_myofibrillar",
        "max_strength",
        "lactate_tolerance",
      ],
      loadBand: "high",
      lactateImpact: "medium",
      cnsLoad: "medium",
    },
    skills: { coordination: "low", balance: "low", techniqueLevel: "medium" },
  },
  {
    id: "gym_eccentric_tempo_rdl",
    name: "Romanian deadlift — eccentric tempo",
    domain: "gym",
    sportTags: ["gym", "hyrox"],
    movementPattern: "hinge",
    muscleGroups: ["posterior_chain", "glutes", "back"],
    equipment: ["barbell"],
    gymMeta: { channels: ["free_weight"], contractions: ["eccentric", "standard"] },
    physiology: {
      primarySystem: "neuromuscular_strength",
      secondarySystems: ["stability"],
      adaptationTargets: ["hypertrophy_myofibrillar", "hypertrophy_mixed", "max_strength", "movement_quality"],
      loadBand: "high",
      lactateImpact: "low",
      cnsLoad: "high",
    },
    skills: { coordination: "medium", balance: "medium", techniqueLevel: "high" },
  },
  {
    id: "gym_wall_sit_isometric",
    name: "Wall sit (isometric)",
    domain: "gym",
    sportTags: ["gym"],
    movementPattern: "isometric_squat",
    muscleGroups: ["quadriceps", "glutes"],
    equipment: ["none"],
    gymMeta: { channels: ["bodyweight"], contractions: ["isometric", "standard"] },
    physiology: {
      primarySystem: "neuromuscular_strength",
      secondarySystems: ["stability"],
      adaptationTargets: ["hypertrophy_sarcoplasmic", "movement_quality", "max_strength", "recovery"],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "low",
    },
    skills: { coordination: "low", balance: "medium", techniqueLevel: "low" },
  },
  {
    id: "gym_box_jump",
    name: "Box jump (progressive)",
    domain: "gym",
    sportTags: ["gym", "crossfit", "hyrox"],
    movementPattern: "jump",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    equipment: ["box", "bodyweight"],
    gymMeta: { channels: ["bodyweight"], contractions: ["plyometric", "standard"] },
    physiology: {
      primarySystem: "neuromuscular_power",
      secondarySystems: ["coordination", "stability"],
      adaptationTargets: ["power_output", "neuromuscular_adaptation", "movement_quality"],
      loadBand: "high",
      lactateImpact: "low",
      cnsLoad: "high",
    },
    skills: { coordination: "high", balance: "high", techniqueLevel: "high" },
  },
  {
    id: "gym_dumbbell_bench",
    name: "Dumbbell bench press",
    domain: "gym",
    sportTags: ["gym", "hyrox"],
    movementPattern: "horizontal_push",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["dumbbell", "bench"],
    gymMeta: { channels: ["free_weight"] },
    physiology: {
      primarySystem: "neuromuscular_strength",
      secondarySystems: ["stability"],
      adaptationTargets: [
        "hypertrophy_mixed",
        "hypertrophy_myofibrillar",
        "hypertrophy_sarcoplasmic",
        "max_strength",
        "neuromuscular_adaptation",
      ],
      loadBand: "high",
      lactateImpact: "medium",
      cnsLoad: "high",
    },
    skills: { coordination: "medium", balance: "medium", techniqueLevel: "medium" },
  },
  {
    id: "crossfit_thruster",
    name: "Thruster",
    domain: "crossfit",
    sportTags: ["crossfit"],
    movementPattern: "squat_to_press",
    muscleGroups: ["quadriceps", "shoulders", "core"],
    equipment: ["barbell", "dumbbell"],
    physiology: {
      primarySystem: "anaerobic_lactic",
      secondarySystems: ["neuromuscular_power", "coordination"],
      adaptationTargets: ["lactate_tolerance", "power_output"],
      loadBand: "very_high",
      lactateImpact: "high",
      cnsLoad: "high",
    },
    skills: { coordination: "high", balance: "medium", techniqueLevel: "high" },
  },
  {
    id: "hyrox_sled_push",
    name: "Sled Push",
    domain: "hyrox",
    sportTags: ["hyrox"],
    movementPattern: "horizontal_push",
    muscleGroups: ["quadriceps", "glutes", "calves", "core"],
    equipment: ["sled"],
    physiology: {
      primarySystem: "anaerobic_lactic",
      secondarySystems: ["neuromuscular_strength", "stability"],
      adaptationTargets: ["lactate_tolerance", "max_strength"],
      loadBand: "high",
      lactateImpact: "high",
      cnsLoad: "high",
    },
    skills: { coordination: "medium", balance: "medium", techniqueLevel: "medium" },
  },
  {
    id: "endurance_z2_cycling",
    name: "Z2 Cycling (road / trainer)",
    domain: "endurance",
    sportTags: ["cycling", "bike", "triathlon", "indoor"],
    movementPattern: "locomotion_steady",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    equipment: ["bike"],
    physiology: {
      primarySystem: "aerobic",
      secondarySystems: ["coordination"],
      adaptationTargets: ["mitochondrial_density", "vo2_max_support", "recovery"],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "low",
    },
    skills: { coordination: "medium", balance: "medium", techniqueLevel: "medium" },
  },
  {
    id: "endurance_cycling_spin_ups",
    name: "Cycling Spin-ups (leg speed)",
    domain: "endurance",
    sportTags: ["cycling", "bike", "indoor"],
    movementPattern: "cadence_drill",
    muscleGroups: ["quadriceps", "calves"],
    equipment: ["bike"],
    physiology: {
      primarySystem: "aerobic",
      secondarySystems: ["neuromuscular_power"],
      adaptationTargets: ["power_output", "movement_quality"],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "medium",
    },
    skills: { coordination: "high", balance: "medium", techniqueLevel: "high" },
  },
  {
    id: "endurance_cycling_recovery_spin",
    name: "Recovery spin (very easy)",
    domain: "endurance",
    sportTags: ["cycling", "bike", "indoor"],
    movementPattern: "locomotion_recovery",
    muscleGroups: ["quadriceps", "calves"],
    equipment: ["bike"],
    physiology: {
      primarySystem: "aerobic",
      secondarySystems: ["mobility"],
      adaptationTargets: ["recovery", "mobility_capacity"],
      loadBand: "low",
      lactateImpact: "low",
      cnsLoad: "low",
    },
    skills: { coordination: "low", balance: "medium", techniqueLevel: "low" },
  },
  {
    id: "endurance_z2_run",
    name: "Z2 Endurance Run",
    domain: "endurance",
    sportTags: ["running", "triathlon"],
    movementPattern: "locomotion_steady",
    muscleGroups: ["posterior_chain", "calves"],
    equipment: ["shoes"],
    physiology: {
      primarySystem: "aerobic",
      secondarySystems: ["mobility", "coordination"],
      adaptationTargets: ["mitochondrial_density", "recovery"],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "low",
    },
    skills: { coordination: "medium", balance: "low", techniqueLevel: "low" },
  },
  {
    id: "soccer_small_sided_game",
    name: "Small-Sided Game 4v4",
    domain: "team_sport",
    sportTags: ["soccer"],
    movementPattern: "intermittent_game",
    muscleGroups: ["total_body"],
    equipment: ["ball", "cones"],
    physiology: {
      primarySystem: "skill",
      secondarySystems: ["anaerobic_lactic", "coordination"],
      adaptationTargets: ["skill_transfer", "lactate_clearance"],
      loadBand: "high",
      lactateImpact: "medium",
      cnsLoad: "medium",
    },
    skills: { coordination: "high", balance: "medium", techniqueLevel: "high" },
  },
  {
    id: "basket_transition_drill",
    name: "Basket Transition Drill",
    domain: "team_sport",
    sportTags: ["basket"],
    movementPattern: "change_of_direction",
    muscleGroups: ["total_body"],
    equipment: ["ball", "cones"],
    physiology: {
      primarySystem: "coordination",
      secondarySystems: ["anaerobic_alactic", "skill"],
      adaptationTargets: ["movement_quality", "skill_transfer"],
      loadBand: "high",
      lactateImpact: "medium",
      cnsLoad: "high",
    },
    skills: { coordination: "high", balance: "high", techniqueLevel: "high" },
  },
  {
    id: "volleyball_jump_sequence",
    name: "Volleyball Jump Sequence",
    domain: "team_sport",
    sportTags: ["volleyball"],
    movementPattern: "jump_landing",
    muscleGroups: ["calves", "quadriceps", "core"],
    equipment: ["court"],
    physiology: {
      primarySystem: "neuromuscular_power",
      secondarySystems: ["proprioception", "skill"],
      adaptationTargets: ["power_output", "movement_quality"],
      loadBand: "high",
      lactateImpact: "low",
      cnsLoad: "high",
    },
    skills: { coordination: "high", balance: "high", techniqueLevel: "medium" },
  },
  {
    id: "boxing_bag_rounds",
    name: "Heavy Bag Intervals",
    domain: "combat",
    sportTags: ["boxing"],
    movementPattern: "striking_interval",
    muscleGroups: ["shoulders", "core", "posterior_chain"],
    equipment: ["bag", "gloves"],
    physiology: {
      primarySystem: "anaerobic_lactic",
      secondarySystems: ["skill", "coordination"],
      adaptationTargets: ["lactate_tolerance", "skill_transfer"],
      loadBand: "very_high",
      lactateImpact: "high",
      cnsLoad: "medium",
    },
    skills: { coordination: "high", balance: "medium", techniqueLevel: "high" },
  },
  {
    id: "karate_kata_precision",
    name: "Kata Precision Set",
    domain: "combat",
    sportTags: ["karate"],
    movementPattern: "technical_sequence",
    muscleGroups: ["total_body"],
    equipment: ["none"],
    physiology: {
      primarySystem: "skill",
      secondarySystems: ["coordination", "stability"],
      adaptationTargets: ["skill_transfer", "movement_quality"],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "medium",
    },
    skills: { coordination: "high", balance: "high", techniqueLevel: "high" },
  },
  {
    id: "mindbody_yoga_flow",
    name: "Yoga Flow vinyasa",
    domain: "mind_body",
    sportTags: ["yoga"],
    movementPattern: "flow_sequence",
    muscleGroups: ["core", "posterior_chain", "shoulders"],
    equipment: ["mat"],
    physiology: {
      primarySystem: "mobility",
      secondarySystems: ["stability", "proprioception"],
      adaptationTargets: ["mobility_capacity", "recovery"],
      loadBand: "low",
      lactateImpact: "low",
      cnsLoad: "low",
    },
    skills: { coordination: "medium", balance: "high", techniqueLevel: "medium" },
  },
  {
    id: "mindbody_pilates_core",
    name: "Pilates Core Sequence",
    domain: "mind_body",
    sportTags: ["pilates"],
    movementPattern: "core_control",
    muscleGroups: ["core", "glutes"],
    equipment: ["mat"],
    physiology: {
      primarySystem: "stability",
      secondarySystems: ["proprioception", "mobility"],
      adaptationTargets: ["movement_quality", "mobility_capacity"],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "low",
    },
    skills: { coordination: "medium", balance: "high", techniqueLevel: "medium" },
  },
  {
    id: "tennis_court_agility",
    name: "Tennis Court Agility & Split-Step",
    domain: "team_sport",
    sportTags: ["tennis"],
    movementPattern: "change_of_direction",
    muscleGroups: ["calves", "quadriceps", "core"],
    equipment: ["court", "cones"],
    physiology: {
      primarySystem: "coordination",
      secondarySystems: ["anaerobic_alactic", "skill"],
      adaptationTargets: ["movement_quality", "skill_transfer"],
      loadBand: "moderate",
      lactateImpact: "medium",
      cnsLoad: "high",
    },
    skills: { coordination: "high", balance: "high", techniqueLevel: "high" },
  },
  {
    id: "judo_kuzushi_drill",
    name: "Judo Kuzushi & Entry Patterns",
    domain: "combat",
    sportTags: ["judo"],
    movementPattern: "technical_sequence",
    muscleGroups: ["total_body"],
    equipment: ["tatami"],
    physiology: {
      primarySystem: "skill",
      secondarySystems: ["coordination", "stability"],
      adaptationTargets: ["skill_transfer", "movement_quality"],
      loadBand: "moderate",
      lactateImpact: "low",
      cnsLoad: "medium",
    },
    skills: { coordination: "high", balance: "high", techniqueLevel: "high" },
  },
  {
    id: "muay_thai_pad_rounds",
    name: "Muay Thai Pad Rounds",
    domain: "combat",
    sportTags: ["muay", "striking"],
    movementPattern: "striking_interval",
    muscleGroups: ["shoulders", "core", "posterior_chain"],
    equipment: ["pads", "gloves"],
    physiology: {
      primarySystem: "anaerobic_lactic",
      secondarySystems: ["skill", "coordination"],
      adaptationTargets: ["lactate_tolerance", "power_output"],
      loadBand: "very_high",
      lactateImpact: "high",
      cnsLoad: "medium",
    },
    skills: { coordination: "high", balance: "medium", techniqueLevel: "high" },
  },
  {
    id: "mindbody_breathwork",
    name: "Breathwork Pattern (nasal / cadence)",
    domain: "mind_body",
    sportTags: ["breathwork", "breath", "meditation"],
    movementPattern: "flow_sequence",
    muscleGroups: ["core", "diaphragm"],
    equipment: ["mat"],
    physiology: {
      primarySystem: "mobility",
      secondarySystems: ["aerobic"],
      adaptationTargets: ["recovery", "mobility_capacity"],
      loadBand: "low",
      lactateImpact: "low",
      cnsLoad: "low",
    },
    skills: { coordination: "low", balance: "medium", techniqueLevel: "low" },
  },
  {
    id: "mindbody_mobility_flow",
    name: "Full-Body Mobility Flow",
    domain: "mind_body",
    sportTags: ["mobility", "stretch", "stretching"],
    movementPattern: "flow_sequence",
    muscleGroups: ["posterior_chain", "shoulders", "hips"],
    equipment: ["mat"],
    physiology: {
      primarySystem: "mobility",
      secondarySystems: ["stability", "proprioception"],
      adaptationTargets: ["mobility_capacity", "movement_quality"],
      loadBand: "low",
      lactateImpact: "low",
      cnsLoad: "low",
    },
    skills: { coordination: "medium", balance: "high", techniqueLevel: "medium" },
  },
];

